# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'first.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.10
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtWidgets import QMainWindow
# from project1.detector.DetectorFrame import DetectorDialog  # 导入自定义的新窗口类
#
#
# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(800, 600)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(300, 300, 200, 50))
#         self.pushButton.setFont(QtGui.QFont("Arial", 14, QtGui.QFont.Bold))
#         self.pushButton.setStyleSheet(
#             "QPushButton {"
#             "   background-color: #003f5c;"
#             "   color: white;"
#             "   border-radius: 10px;"
#             "   border: 2px solid #003f5c;"
#             "}"
#             "QPushButton:hover {"
#             "   background-color: #005f87;"
#             "}"
#             "QPushButton:pressed {"
#             "   background-color: #002f3e;"
#             "}"
#         )
#         self.pushButton.setObjectName("pushButton")
#         self.pushButton.setText("车流量检测")
#
#         self.label_2 = QtWidgets.QLabel(self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(200, 150, 400, 100))
#         self.label_2.setFont(QtGui.QFont("Arial", 24, QtGui.QFont.Bold))
#         self.label_2.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_2.setObjectName("label_2")
#         self.label_2.setText("人车流量检测系统")
#
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#
#         self.retranslateUi(MainWindow)
#
#         self.pushButton.clicked.connect(MainWindow.goin)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "人车流量检测系统"))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from detector.carFrame import CarDialog  # 导入自定义的新窗口类


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 300, 200, 50))
        self.pushButton.setFont(QtGui.QFont("Arial", 14, QtGui.QFont.Bold))
        self.pushButton.setStyleSheet(
            "QPushButton {"
            "   background-color: #003f5c;"
            "   color: white;"
            "   border-radius: 10px;"
            "   border: 2px solid #003f5c;"
            "}"
            "QPushButton:hover {"
            "   background-color: #005f87;"
            "}"
            "QPushButton:pressed {"
            "   background-color: #002f3e;"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("车流量检测")

        self.pushButton_people = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_people.setGeometry(QtCore.QRect(300, 380, 200, 50))
        self.pushButton_people.setFont(QtGui.QFont("Arial", 14, QtGui.QFont.Bold))
        self.pushButton_people.setStyleSheet(
            "QPushButton {"
            "   background-color: #003f5c;"
            "   color: white;"
            "   border-radius: 10px;"
            "   border: 2px solid #003f5c;"
            "}"
            "QPushButton:hover {"
            "   background-color: #005f87;"
            "}"
            "QPushButton:pressed {"
            "   background-color: #002f3e;"
            "}"
        )
        self.pushButton_people.setObjectName("pushButton_people")
        self.pushButton_people.setText("人流量检测")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 150, 400, 100))
        self.label_2.setFont(QtGui.QFont("Arial", 24, QtGui.QFont.Bold))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.setText("人车流量检测系统")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton.clicked.connect(MainWindow.goin)
        self.pushButton_people.clicked.connect(MainWindow.goin_people)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人车流量检测系统"))
